name: apply

on:
  push:
    branches:
      - main
    paths:
      - "*.tf"
      - ".github/workflows/apply.yml"

permissions:
  id-token: write
  contents: read

env:
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
  SLACK_USERNAME: github
  SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}

jobs:
  apply:
    name: Apply
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.BACKEND_ASSUME_ROLE_ARN }}
          role-session-name: github-actions-terraform-apply-session
          aws-region: ap-northeast-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ secrets.TF_VERSION }}

      - name: Terraform Init
        run: terraform init -backend-config "bucket=${{ secrets.BACKEND_S3_BUCKET }}"

      - name: Terraform Apply
        run: terraform apply -auto-approve -var "assume_role_arn=${{ secrets.ASSUME_ROLE_ARN }}"

      - name: Success Apply Job
        if: ${{ success() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_TITLE: Success Apply Job
          SLACK_COLOR: good

      - name: Failure Apply Job
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_TITLE: Failure Apply Job
          SLACK_COLOR: danger
