name: tfsec

on:
  pull_request:
    branches:
      - main
    paths:
      - "*.tf"
      - ".github/workflows/tfsec.yml"

jobs:
  tfsec:
    name: TFSec
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: TFSec
        uses: reviewdog/action-tfsec@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_error: true
          filter_mode: nofilter
